# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myrailsblog_development
  host: localhost
  username: postgres
  password: umiwoabi

test:
  <<: *default
  database: myrailsblog_test
  host: localhost
  username: postgres
  password: umiwoabi

# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  <<: *default
  database: myrailsblog_production
  username: myrailsblog
  password: umiwoabi
